### ISSUE TITLE
Basic backend implementation. Set up the backend development environment and create mock endpoints for /friends and /groups, allowing the frontend to connect and receive mock data.

### ISSUE THREAD

**Issue by jdcastellanosb73** [ISIS3510-202410-Team-13/Backend#15]
this feature should be implemented before [06/04]

**Comment by jsurrea** [comment]
Hey @SnowArtz @iGotty! Can we close this issue? I think it is a duplicate of the PR you submitted

**Comment by SnowArtz** [comment]
@jsurrea Yes, you are right, this is a duplicate of a PR that was already implemented and solve it. I close the issue,
