### ISSUE TITLE
Improve documentation of GroupsFriendsEvents micro-service

### ISSUE THREAD

**Issue by jsurrea** [ISIS3510-202410-Team-13/Backend#22]
I think it would be great to create a README file for this service, in which we specify the endpoints, the parameters and the expected responses given by the service. This will help us solve bugs more efficiently!

Also, can you create a small end-point /health to run tests in the App? This will help me to diagnose bugs better. You can implement it just like this snippet!

```TypeScript
app.get("/health", (req: Request, res: Response) => {
   res.status(200).send("GroupsFriendsEvents Server is running").end();
 })
```

**Comment by jsurrea** [comment]
@SnowArtz @iGotty Can you take a look at this?

**Comment by SnowArtz** [comment]
> @SnowArtz @iGotty Can you take a look at this?

Perfect, we are going to work in the micro-service documentation and the proposed end-point implementation.
