### ISSUE TITLE
Re-deploy GroupsFriendsEvents in Google App Engine

### ISSUE THREAD

**Issue by jsurrea** [ISIS3510-202410-Team-13/Backend#24]
Currently, GroupsFriendsEvents is deployed as the default service. This can cause errors if someone overwrites this service when deploying another one. For this reason, I propose to redeploy this and update any reference to its endpoints.

This can be achieved by adding the following to `app.yaml`: `service: "groups-friends-events"`
See the example for `available-spaces`

**Comment by jsurrea** [comment]
@SnowArtz @iGotty Can you take a look at this?

**Comment by SnowArtz** [comment]
> @SnowArtz @iGotty Can you take a look at this?

Hi @jsurrea, I will check it! I agree with you,

**Comment by jsurrea** [comment]
Deprioritized to avoid unexpected bugs during this sprint

**Comment by jsurrea** [comment]
Won't due because current implementation works correctly and is not a priority at the moment.
